/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuggestionsRouteImport } from './routes/suggestions'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RecipesRouteImport } from './routes/recipes'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as GroceriesRouteImport } from './routes/groceries'
import { Route as IndexRouteImport } from './routes/index'

const SuggestionsRoute = SuggestionsRouteImport.update({
  id: '/suggestions',
  path: '/suggestions',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const GroceriesRoute = GroceriesRouteImport.update({
  id: '/groceries',
  path: '/groceries',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/groceries': typeof GroceriesRoute
  '/inventory': typeof InventoryRoute
  '/recipes': typeof RecipesRoute
  '/reports': typeof ReportsRoute
  '/suggestions': typeof SuggestionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/groceries': typeof GroceriesRoute
  '/inventory': typeof InventoryRoute
  '/recipes': typeof RecipesRoute
  '/reports': typeof ReportsRoute
  '/suggestions': typeof SuggestionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/groceries': typeof GroceriesRoute
  '/inventory': typeof InventoryRoute
  '/recipes': typeof RecipesRoute
  '/reports': typeof ReportsRoute
  '/suggestions': typeof SuggestionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/groceries'
    | '/inventory'
    | '/recipes'
    | '/reports'
    | '/suggestions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/groceries'
    | '/inventory'
    | '/recipes'
    | '/reports'
    | '/suggestions'
  id:
    | '__root__'
    | '/'
    | '/groceries'
    | '/inventory'
    | '/recipes'
    | '/reports'
    | '/suggestions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GroceriesRoute: typeof GroceriesRoute
  InventoryRoute: typeof InventoryRoute
  RecipesRoute: typeof RecipesRoute
  ReportsRoute: typeof ReportsRoute
  SuggestionsRoute: typeof SuggestionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suggestions': {
      id: '/suggestions'
      path: '/suggestions'
      fullPath: '/suggestions'
      preLoaderRoute: typeof SuggestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groceries': {
      id: '/groceries'
      path: '/groceries'
      fullPath: '/groceries'
      preLoaderRoute: typeof GroceriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GroceriesRoute: GroceriesRoute,
  InventoryRoute: InventoryRoute,
  RecipesRoute: RecipesRoute,
  ReportsRoute: ReportsRoute,
  SuggestionsRoute: SuggestionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
