"""updated pantry_status

Revision ID: 110d82e558e1
Revises: 9b2cec66a4ec
Create Date: 2025-08-01 11:05:57.664973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '110d82e558e1'
down_revision = '9b2cec66a4ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pantry_entry', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.Enum('IN_STOCK', 'DISCARDED', 'USED', name='pantrystatus', native_enum=False),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pantry_entry', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('IN_STOCK', 'DISCARDED', 'USED', name='pantrystatus', native_enum=False),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)

    # ### end Alembic commands ###
