"""add pantry items table

Revision ID: 6548e8406c67
Revises: f88440d5231e
Create Date: 2025-07-15 22:11:19.646097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6548e8406c67'
down_revision = 'f88440d5231e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pantry_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('date_added', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('IN_STOCK', 'LOW', 'OUT_OF_STOCK', 'EXPIRED', name='pantrystatus', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pantry_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pantry_entry_ingredient_id'), ['ingredient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pantry_entry_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aisle', sa.String(length=64), nullable=False))
        batch_op.create_index(batch_op.f('ix_ingredient_aisle'), ['aisle'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingredient_aisle'))
        batch_op.drop_column('aisle')

    with op.batch_alter_table('pantry_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pantry_entry_user_id'))
        batch_op.drop_index(batch_op.f('ix_pantry_entry_ingredient_id'))

    op.drop_table('pantry_entry')
    # ### end Alembic commands ###
