"""update Recipe model

Revision ID: aabacc80b187
Revises: 0b7678d45481
Create Date: 2025-07-17 21:18:48.659583

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'aabacc80b187'
down_revision = '0b7678d45481'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instructions', sa.JSON(), nullable=True))
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sqlite.JSON(), nullable=True))
        batch_op.drop_column('instructions')

    # ### end Alembic commands ###
