"""empty message

Revision ID: e87305ea52dd
Revises: 0b7678d45481
Create Date: 2025-07-17 20:26:49.339149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e87305ea52dd'
down_revision = '0b7678d45481'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipe_name'))
        batch_op.create_index(batch_op.f('ix_recipe_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipe_name'))
        batch_op.create_index(batch_op.f('ix_recipe_name'), ['name'], unique=1)

    # ### end Alembic commands ###
