"""added product_name field

Revision ID: eb27e4c30c63
Revises: aabacc80b187
Create Date: 2025-07-19 17:56:59.517144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb27e4c30c63'
down_revision = 'aabacc80b187'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pantry_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pantry_entry', schema=None) as batch_op:
        batch_op.drop_column('product_name')

    # ### end Alembic commands ###
