"""Recipe table

Revision ID: f88440d5231e
Revises: 93b4ccc3695a
Create Date: 2025-07-03 23:57:22.804599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f88440d5231e'
down_revision = '93b4ccc3695a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=64), nullable=False))
        batch_op.create_index(batch_op.f('ix_recipe_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipe_name'))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
